export const siteConfig = {
  name: "ARJE Digital",
  tagline: "Digital tools for accounting professionals",
  description: "Templates, automations, and SaaS tools for bookkeepers, tax preparers, and Amazon FBA sellers. Built by a PTIN-certified tax professional managing 90+ clients.",
  url: "https://arjebookkeeping.com",
  email: "arnold@arjebookkeeping.com",
  location: "Henderson, Nevada",
  social: {
    linkedin: "https://linkedin.com/in/arnolddizon",
    pinterest: "https://pinterest.com/arjebookkeeping",
    youtube: "https://youtube.com/@ARJEBookkeeping",
    twitter: "https://twitter.com/arjebookkeeping",
    gumroad: "https://arjebookkeeping.gumroad.com",
  },
}

export const products = [
  {
    id: "automation-bundle",
    name: "Bookkeeper's Automation Bundle",
    price: "$197",
    priceNum: 197,
    tag: "Best Seller",
    tagColor: "amber",
    description: "Complete practice automation system. Client onboarding, tracking, email sequences, Amazon seller tools. Everything you need to run a 50+ client practice on autopilot.",
    features: [
      "Tax Prep Client Onboarding System ($97 value)",
      "Amazon Seller Bookkeeping Templates ($47 value)",
      "Client Outreach Templates ($27 value)",
      "Video Tutorial Library (included)",
    ],
    platform: "Gumroad",,
    category: "Bundles",
    clickbank: true,
    href: "/automation-bundle",
  },
  {
    id: "tax-prep-onboarding",
    name: "Tax Prep Client Onboarding System",
    price: "$97",
    priceNum: 97,
    tag: "Popular",
    tagColor: "blue",
    description: "JotForm templates, 4 Zapier automations, email sequences, client tracking, WISP template. Onboard new tax clients in under 10 minutes.",
    features: [
      "Complete setup guide",
      "Pre-built JotForm intake templates",
      "4 Zapier automations",
      "Email templates for every stage",
      "Client tracking spreadsheet",
      "WISP template",
    ],
    platform: "Gumroad",
    category: "Tax Prep",
    href: "https://arjebookkeeping.gumroad.com/l/taxprepsetup",
  },
  {
    id: "amazon-seller-templates",
    name: "Amazon Seller Bookkeeping Templates",
    price: "$47",
    priceNum: 47,
    tag: "",
    tagColor: "",
    description: "P&L tracker, inventory management, fee calculator, and quarterly tax estimator built specifically for FBA sellers.",
    features: [
      "Profit & Loss tracker for Amazon",
      "Inventory management spreadsheet",
      "Amazon fee calculator",
      "Quarterly tax estimator",
    ],
    platform: "Gumroad",
    category: "Amazon FBA",
    href: "https://arjebookkeeping.gumroad.com/l/eercnn",
  },
  {
    id: "bos-starter-kit",
    name: "BOS Starter Kit",
    price: "$49",
    priceNum: 49,
    tag: "New",
    tagColor: "green",
    description: "Business Operating System foundation. Folder structure, BOS tracker spreadsheet, month-end close checklist, and quick start guide.",
    features: [
      "Folder structure template",
      "BOS Tracker spreadsheet",
      "Month-end close checklist",
      "Quick start guide",
    ],
    platform: "Gumroad",
    category: "Business Systems",
    href: "https://arjebookkeeping.gumroad.com",
  },
  {
    id: "tax-tracking-spreadsheet",
    name: "Tax Prep Client Tracking Spreadsheet",
    price: "$27",
    priceNum: 27,
    tag: "",
    tagColor: "",
    description: "Google Sheets client tracker with status, deadlines, document checklist, and fee tracking. Never lose track of a client again.",
    features: [
      "Client status dashboard",
      "Document checklist per client",
      "Deadline tracking",
      "Fee tracking and invoicing",
    ],
    platform: "Gumroad",
    category: "Tax Prep",
    href: "https://arjebookkeeping.gumroad.com/l/pwvlyz",
  },
  {
    id: "tax-email-templates",
    name: "Tax Prep Email Templates",
    price: "$19",
    priceNum: 19,
    tag: "Starter",
    tagColor: "purple",
    description: "Professional email templates for every stage of the tax prep client relationship. Copy, paste, customize, send.",
    features: [
      "Welcome emails",
      "Document request templates",
      "Status update templates",
      "Follow-up sequences",
    ],
    platform: "Gumroad",
    category: "Tax Prep",
    href: "https://arjebookkeeping.gumroad.com/l/fvmjdu",
  },
]

export const categories = ["All", "Bundles", "Tax Prep", "Amazon FBA", "Business Systems"]

export const stats = [
  { value: "90+", label: "Active clients" },
  { value: "3+", label: "Years in practice" },
  { value: "38+", label: "Digital products" },
  { value: "$0/mo", label: "Software cost" },
]

export const platforms = [
  { name: "Gumroad", href: "https://arjebookkeeping.gumroad.com" },
  { name: "Etsy", href: "#" },
  { name: "ClickBank", href: "#" },
  { name: "ClaudeSkills.ai", href: "#" },
]
