export const siteConfig = {
    name: "ARJE Digital",
    tagline: "Digital tools for accounting professionals",
    description: "Templates, automations, and SaaS tools for bookkeepers, tax preparers, and Amazon FBA sellers. Built by a PTIN-certified tax professional managing 90+ clients.",
    url: "https://arjebookkeeping.com",
    email: "arnold@arjebookkeeping.com",
    location: "Henderson, Nevada",
    social: {
          linkedin: "https://www.linkedin.com/in/arnold-dizon-4b045a3a9/",
          pinterest: "https://pinterest.com/arjebookkeeping",
          twitter: "https://twitter.com/arjebookkeeping",
          gumroad: "https://arjebookkeeping.gumroad.com",
          etsy: "https://www.etsy.com/shop/ARJEDigitalTools",
          amazonAuthor: "https://www.amazon.com/author/arnolddizon",
    },
}

export const products = [
  {
        id: "automation-bundle",
        name: "Bookkeeper's Automation Bundle",
        price: "$197",
        priceNum: 197,
        tag: "Best Seller",
        tagColor: "amber",
        description: "Complete practice automation system. Client onboarding, tracking, email sequences, Amazon seller tools. Everything you need to run a 50+ client practice on autopilot.",
        features: [
                "Tax Prep Client Onboarding System ($97 value)",
                "Amazon Seller Bookkeeping Templates ($47 value)",
                "Client Outreach Templates ($27 value)",
                "Video Tutorial Library (included)",
              ],
        platform: "Gumroad",
        category: "Bundles",
        href: "/automation-bundle",
  },
  {
        id: "tax-prep-onboarding",
        name: "Tax Prep Client Onboarding System",
        price: "$97",
        priceNum: 97,
        tag: "Popular",
        tagColor: "blue",
        description: "JotForm templates, 4 Zapier automations, email sequences, client tracking, WISP template. Onboard new tax clients in under 10 minutes.",
        features: [
                "Complete setup guide",
                "Pre-built JotForm intake templates",
                "4 Zapier automations",
                "Email templates for every stage",
                "Client tracking spreadsheet",
                "WISP template",
              ],
        platform: "Gumroad",
        category: "Tax Prep",
        href: "https://arjebookkeeping.gumroad.com/l/taxprepsetup",
  },
  {
        id: "amazon-seller-templates",
        name: "Amazon Seller Bookkeeping Templates",
        price: "$47",
        priceNum: 47,
        tag: "",
        tagColor: "",
        description: "P&L tracker, inventory management, fee calculator, and quarterly tax estimator built specifically for FBA sellers.",
        features: [
                "Profit & Loss tracker for Amazon",
                "Inventory management spreadsheet",
                "Amazon fee calculator",
                "Quarterly tax estimator",
              ],
        platform: "Gumroad",
        category: "Amazon FBA",
        href: "https://arjebookkeeping.gumroad.com/l/eercnn",
  },
  {
        id: "bos-starter-kit",
        name: "BOS Starter Kit",
        price: "$49",
        priceNum: 49,
        tag: "New",
        tagColor: "green",
        description: "Business Operating System foundation. Folder structure, BOS tracker spreadsheet, month-end close checklist, and quick start guide.",
        features: [
                "Folder structure template",
                "BOS Tracker spreadsheet",
                "Month-end close checklist",
                "Quick start guide",
              ],
        platform: "Gumroad",
        category: "Business Systems",
        href: "https://arjebookkeeping.gumroad.com",
  },
  {
        id: "tax-tracking-spreadsheet",
        name: "Tax Prep Client Tracking Spreadsheet",
        price: "$27",
        priceNum: 27,
        tag: "",
        tagColor: "",
        description: "Google Sheets client tracker with status, deadlines, document checklist, and fee tracking. Never lose track of a client again.",
        features: [
                "Client status dashboard",
                "Document checklist per client",
                "Deadline tracking",
                "Fee tracking and invoicing",
              ],
        platform: "Gumroad",
        category: "Tax Prep",
        href: "https://arjebookkeeping.gumroad.com/l/pwvlyz",
  },
  {
        id: "tax-email-templates",
        name: "Tax Prep Email Templates",
        price: "$19",
        priceNum: 19,
        tag: "Starter",
        tagColor: "purple",
        description: "Professional email templates for every stage of the tax prep client relationship. Copy, paste, customize, send.",
        features: [
                "Welcome emails",
                "Document request templates",
                "Status update templates",
                "Follow-up sequences",
              ],
        platform: "Gumroad",
        category: "Tax Prep",
        href: "https://arjebookkeeping.gumroad.com/l/fvmjdu",
  },
  {
        id: "fba-reimbursement-calculator",
        slug: "fba-reimbursement-calculator",
        name: "FBA Reimbursement Calculator",
        price: "$19.99",
        priceNum: 19.99,
        tag: "Mini App",
        tagColor: "blue",
        description: "Calculate exactly what Amazon owes you in lost, damaged, or destroyed FBA inventory. Built for sellers and bookkeepers who need to file accurate reimbursement claims.",
        subhead: "Know what Amazon owes you before you file the claim.",
        features: [
                "Loss type classification (lost, damaged, destroyed, customer return)",
                "Per-unit reimbursement rate calculator",
                "Time-window eligibility check (18-month FBA rule)",
                "Total claim summary with itemized breakdown",
                "PDF export for submission to Amazon",
                "Browser-based, works offline, no install",
              ],
        platform: "Etsy + Gumroad",
        category: "Amazon FBA",
        tags: ["Interactive Tool"],
        href: "/products/fba-reimbursement-calculator",
        etsyUrl: "",
        gumroadUrl: "https://arjebookkeeping.gumroad.com/l/fba-reimbursement-calculator",
        coverImage: "/products/fba-reimbursement-calculator/cover.png",
        icp: "FBA_SELLER",
        faqs: [
                { q: "How is reimbursement different from refunds?", a: "Reimbursements are what Amazon owes YOU as the seller for inventory they lost or damaged in their warehouses. Refunds are what you owe customers. Different process, different forms." },
                { q: "What's the time window for filing?", a: "Amazon's FBA reimbursement policy generally requires filing within 18 months of the inventory event. The calculator includes an eligibility check." },
                { q: "Does this submit claims for me?", a: "No. This calculates what you're owed so you can file accurate claims through Amazon Seller Central. Amazon doesn't allow third-party automated submissions." },
              ],
  },
  {
        id: "bookkeeper-capacity-calculator",
        slug: "bookkeeper-capacity-calculator",
        name: "Bookkeeper Capacity Calculator",
        price: "$19.99",
        priceNum: 19.99,
        tag: "Mini App",
        tagColor: "blue",
        description: "Find your real client ceiling in 60 seconds. Models hours per client, hours per week, and target revenue to expose the capacity wall most bookkeepers hit at 12-15 clients.",
        subhead: "Find your real client ceiling in 60 seconds.",
        features: [
                "Hours-per-client capacity math",
                "Target revenue back-calculation",
                "Headroom percentage display",
                "Hourly rate sanity check vs industry medians",
                "Pricing-shift recommendation engine",
                "Browser-based, works offline, instant calc",
              ],
        platform: "Etsy + Gumroad",
        category: "Practice Management",
        tags: ["Interactive Tool"],
        href: "/products/bookkeeper-capacity-calculator",
        etsyUrl: "",
        gumroadUrl: "https://arjebookkeeping.gumroad.com/l/bookkeeper-capacity-calculator",
        coverImage: "/products/bookkeeper-capacity-calculator/cover.png",
        icp: "BOOKKEEPER",
        faqs: [
                { q: "How is this different from the Solo CPA Capacity Calculator?", a: "This one does flat hours-per-client math - perfect for bookkeepers whose workload spreads year-round. The Solo CPA version (sister tool, $29) adds tax-season hour-spike modeling and attest practice mode for CPAs running compliance + advisory practices." },
                { q: "What's a realistic capacity for a solo bookkeeper?", a: "Most solo bookkeepers hit a wall around 12-15 clients at 50+ hours/week. The calculator exposes exactly where YOUR wall is based on your hours and rates." },
                { q: "Can I save my inputs?", a: "The calculator runs in browser memory only. Use the PDF export to save results." },
              ],
  },
  {
        id: "quarterly-estimated-tax-calculator",
        slug: "quarterly-estimated-tax-calculator",
        name: "Quarterly Estimated Tax Calculator",
        price: "$24.99",
        priceNum: 24.99,
        tag: "Mini App",
        tagColor: "blue",
        description: "Hand to clients to estimate Q1-Q4 federal estimated taxes. Reduces 'how much do I owe?' emails from self-employed clients during tax season.",
        subhead: "Stop answering 'how much do I owe?' emails.",
        features: [
                "Q1-Q4 estimated payment calculator",
                "Self-employment tax (15.3% SE) handled correctly",
                "Federal income tax bracket math (2026 rates)",
                "Standard vs itemized deduction toggle",
                "Safe harbor check (100% / 110% prior-year tax based on AGI)",
                "PDF export with payment voucher info",
              ],
        platform: "Etsy + Gumroad",
        category: "Tax Prep",
        tags: ["Interactive Tool"],
        href: "/products/quarterly-estimated-tax-calculator",
        etsyUrl: "",
        gumroadUrl: "https://arjebookkeeping.gumroad.com/l/quarterly-estimated-tax-calculator",
        coverImage: "/products/quarterly-estimated-tax-calculator/cover.png",
        icp: "TAX_PREPARER",
        faqs: [
                { q: "Does this handle state estimated taxes?", a: "No. This is federal-only (Form 1040-ES). State estimated tax requirements vary widely - consult your state tax authority or a tax professional for state amounts." },
                { q: "Is the safe harbor rule applied automatically?", a: "Yes. The calculator flags whether your estimates meet the IRS safe harbor: 100% of prior-year tax if your prior-year AGI was $150,000 or less, or 110% if AGI was over $150,000. Meeting safe harbor avoids underpayment penalties even if you owe more at filing." },
                { q: "Can I use this for myself, or only clients?", a: "Both. Many tax prep professionals use it for their own quarterly planning AND give it to clients. License is personal/business use, not redistribution." },
              ],
  },
  {
        id: "monthly-close-checklist-calculator",
        slug: "monthly-close-checklist-calculator",
        name: "Monthly Close Checklist Calculator",
        price: "$19.99",
        priceNum: 19.99,
        tag: "Mini App",
        tagColor: "blue",
        description: "Time-budgets each step of the monthly close cycle. Useful for staff capacity planning and identifying bottlenecks in your close process.",
        subhead: "Time-budget every step of monthly close.",
        features: [
                "Step-by-step close checklist (bank rec, AR, AP, inventory, accruals)",
                "Hours-per-step time budgeting",
                "Total close cycle time projection",
                "Bottleneck identification (which step eats most time)",
                "Staff capacity planning view",
                "PDF export of personalized checklist",
              ],
        platform: "Etsy + Gumroad",
        category: "Practice Management",
        tags: ["Interactive Tool"],
        href: "/products/monthly-close-checklist-calculator",
        etsyUrl: "",
        gumroadUrl: "https://arjebookkeeping.gumroad.com/l/monthly-close-checklist-calculator",
        coverImage: "/products/monthly-close-checklist-calculator/cover.png",
        icp: "BOOKKEEPER",
        faqs: [
                { q: "Is this for solo bookkeepers or firms?", a: "Both work. Solo bookkeepers use it for personal time budgeting; firms use it for staff capacity planning and identifying who's bottlenecked on which step." },
                { q: "Does it integrate with QuickBooks or Xero?", a: "No - this is a standalone calculator and checklist. Outputs a printable PDF you reference alongside whatever bookkeeping software you use." },
                { q: "Can I customize the checklist steps?", a: "Yes. The default checklist covers standard close steps; each is editable in the calculator before you save the PDF." },
              ],
  },
  {
        id: "solo-cpa-client-capacity-calculator",
        slug: "solo-cpa-client-capacity-calculator",
        name: "Solo CPA Client Capacity Calculator",
        price: "$29",
        priceNum: 29,
        tag: "New",
        tagColor: "green",
        description: "Models compliance vs advisory revenue mix, tax-season hour spikes, and attest practice constraints. Dual capacity ceilings expose the bottleneck most calculators hide.",
        subhead: "Plan for tax season before tax season plans for you.",
        features: [
                "Compliance vs advisory revenue mix modeling",
                "Tax-season hour spike multiplier (default 3.5x, editable)",
                "Attest practice mode: CPE + peer review + independence flags",
                "Dual capacity ceilings (off-season AND tax-season)",
                "Sensitivity table (2.5x / 3.5x / 4.5x scenarios)",
                "Mix shift recommendation engine",
                "Hourly rate sanity checks vs industry medians",
                "Burnout warning at 130%+ tax-season utilization",
              ],
        platform: "Etsy + Gumroad",
        category: "Practice Management",
        tags: ["Interactive Tool"],
        href: "/products/solo-cpa-client-capacity-calculator",
        etsyUrl: "https://www.etsy.com/listing/4494612997/solo-cpa-capacity-calculator-compliance",
        gumroadUrl: "https://arjebookkeeping.gumroad.com/l/solo-cpa-client-capacity-calculator",
        coverImage: "/products/solo-cpa-client-capacity-calculator/cover.png",
        icp: "SOLO_CPA",
        faqs: [
                { q: "How is this different from the Bookkeeper Capacity Calculator?", a: "Structurally different math. The Bookkeeper version does flat hours/client capacity. This one models compliance and advisory work separately (different economics), adds tax-season hour-spike modeling, and has a dedicated attest practice mode. Different ICP, different math, different price." },
                { q: "Does it determine independence under AICPA rules?", a: "No. The tool flags potential client overlaps between your compliance and advisory rosters; it does not determine independence. Review each overlap with your peer review committee or state board." },
                { q: "Why is it $29 when other capacity calculators are $19.99?", a: "Different ICP, structurally different math, different willingness-to-pay. Solo CPAs benchmark against tools like Canopy/Karbon/TaxDome at $30-80/MONTH. A $29 one-time calculator reads as a steal." },
              ],
  },
  ]

export const categories = ["All", "Interactive Tools", "Bundles", "Tax Prep", "Practice Management", "Amazon FBA", "Business Systems"]

export const stats = [
  { value: "90+", label: "Active clients" },
  { value: "Since 2021", label: "In practice" },
  { value: "50+", label: "Digital products" },
  { value: "$0/mo", label: "Software cost" },
  ]

export const platforms = [
  { name: "Gumroad", href: "https://arjebookkeeping.gumroad.com" },
  { name: "Etsy", href: "https://www.etsy.com/shop/ARJEDigitalTools" },
  { name: "Free Resources", href: "https://kb.arjebookkeeping.com" },
  ]
